
package soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuctionWS", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:8080/AuctionWS/AuctionWS?WSDL")
public class AuctionWS_Service
    extends Service
{

    private final static URL AUCTIONWS_WSDL_LOCATION;
    private final static WebServiceException AUCTIONWS_EXCEPTION;
    private final static QName AUCTIONWS_QNAME = new QName("http://soap/", "AuctionWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/AuctionWS/AuctionWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUCTIONWS_WSDL_LOCATION = url;
        AUCTIONWS_EXCEPTION = e;
    }

    public AuctionWS_Service() {
        super(__getWsdlLocation(), AUCTIONWS_QNAME);
    }

    public AuctionWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUCTIONWS_QNAME, features);
    }

    public AuctionWS_Service(URL wsdlLocation) {
        super(wsdlLocation, AUCTIONWS_QNAME);
    }

    public AuctionWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUCTIONWS_QNAME, features);
    }

    public AuctionWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuctionWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuctionWS
     */
    @WebEndpoint(name = "AuctionWSPort")
    public AuctionWS getAuctionWSPort() {
        return super.getPort(new QName("http://soap/", "AuctionWSPort"), AuctionWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuctionWS
     */
    @WebEndpoint(name = "AuctionWSPort")
    public AuctionWS getAuctionWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "AuctionWSPort"), AuctionWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUCTIONWS_EXCEPTION!= null) {
            throw AUCTIONWS_EXCEPTION;
        }
        return AUCTIONWS_WSDL_LOCATION;
    }

}
