
package soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuctionWS", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuctionWS {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns soap.SetBidStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bidForAuction", targetNamespace = "http://soap/", className = "soap.BidForAuction")
    @ResponseWrapper(localName = "bidForAuctionResponse", targetNamespace = "http://soap/", className = "soap.BidForAuctionResponse")
    @Action(input = "http://soap/AuctionWS/bidForAuctionRequest", output = "http://soap/AuctionWS/bidForAuctionResponse")
    public SetBidStatus bidForAuction(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        long arg2);

    /**
     * 
     * @return
     *     returns java.util.List<soap.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActiveAuctions", targetNamespace = "http://soap/", className = "soap.GetActiveAuctions")
    @ResponseWrapper(localName = "getActiveAuctionsResponse", targetNamespace = "http://soap/", className = "soap.GetActiveAuctionsResponse")
    @Action(input = "http://soap/AuctionWS/getActiveAuctionsRequest", output = "http://soap/AuctionWS/getActiveAuctionsResponse")
    public List<Product> getActiveAuctions();

}
